# Generated by Django 6.0.2 on 2026-02-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('gols', models.PositiveIntegerField(default=0)),
                ('partidas_jogadas', models.PositiveIntegerField(default=0)),
                ('partidas_vencidas', models.PositiveIntegerField(default=0)),
                ('pct_vitorias', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-gols', 'nome'],
            },
        ),
    ]
